version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:vishwas1660@db.nfegitlbxqxsnbzxiteq.supabase.co:5432/postgres
      PYTHONUNBUFFERED: 1
    volumes:
      - ./app:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
